Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,7 +43,14 @@ jobs:
             -archivePath build/ios/archive/Runner.xcarchive \
             clean archive \
             CODE_SIGN_STYLE=Automatic
-          
+
+      - name: Check if archive exists
+        run: |
+          if [ ! -d "build/ios/archive/Runner.xcarchive" ]; then
+            echo "Archive not found! Exiting..."
+            exit 1
+          fi
+
       - name: Export .ipa
         run: |
           xcodebuild \
